/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['accessToken', 'accessTokenExpiresAt', 'accountId', 'createdAt', 'id', 'idToken', 'issuer', 'password', 'providerId', 'refreshToken', 'refreshTokenExpiresAt', 'scope', 'updatedAt', 'userId'] as const
  $columns = AccountSchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime()
  declare accessTokenExpiresAt: DateTime | null
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idToken: string | null
  @column()
  declare issuer: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare providerId: string
  @column()
  declare refreshToken: string | null
  @column.dateTime()
  declare refreshTokenExpiresAt: DateTime | null
  @column()
  declare scope: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class AiJobSchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'createdBy', 'dismissedAt', 'errorType', 'finishedAt', 'householdId', 'id', 'input', 'kind', 'lockedAt', 'progress', 'result', 'runAt', 'startedAt', 'status', 'traceparent'] as const
  $columns = AiJobSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare dismissedAt: DateTime | null
  @column()
  declare errorType: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare input: any
  @column()
  declare kind: string
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column()
  declare progress: any
  @column()
  declare result: any | null
  @column.dateTime()
  declare runAt: DateTime
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare traceparent: string | null
}

export class AiProviderSettingSchema extends BaseModel {
  static $columns = ['activeProvider', 'householdId', 'id', 'updatedAt', 'updatedBy'] as const
  $columns = AiProviderSettingSchema.$columns
  @column()
  declare activeProvider: string
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class AiUsageSchema extends BaseModel {
  static $columns = ['count', 'householdId', 'period'] as const
  $columns = AiUsageSchema.$columns
  @column()
  declare count: number
  @column({ isPrimary: true })
  declare householdId: string
  @column()
  declare period: string
}

export class HomeAssistantLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'direction', 'enabled', 'encryptedToken', 'householdId', 'id', 'instanceUrl', 'lastError', 'lastSyncAt', 'todoEntityId', 'todoEntityName', 'updatedAt'] as const
  $columns = HomeAssistantLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare direction: string
  @column()
  declare enabled: boolean
  @column()
  declare encryptedToken: string
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare instanceUrl: string
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastSyncAt: DateTime | null
  @column()
  declare todoEntityId: string | null
  @column()
  declare todoEntityName: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HouseholdSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'inviteCode', 'name', 'ownerId', 'updatedAt'] as const
  $columns = HouseholdSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inviteCode: string
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HouseholdMemberSchema extends BaseModel {
  static $columns = ['householdId', 'id', 'joinedAt', 'role', 'userId'] as const
  $columns = HouseholdMemberSchema.$columns
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare role: string
  @column()
  declare userId: string
}

export class HouseholdSubscriptionSchema extends BaseModel {
  static $columns = ['cancelAtPeriodEnd', 'expiresAt', 'householdId', 'payerUserId', 'stripeCustomerId', 'stripeSubscriptionId', 'updatedAt'] as const
  $columns = HouseholdSubscriptionSchema.$columns
  @column()
  declare cancelAtPeriodEnd: boolean
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare householdId: string
  @column()
  declare payerUserId: string | null
  @column()
  declare stripeCustomerId: string | null
  @column()
  declare stripeSubscriptionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PasskeySchema extends BaseModel {
  static $columns = ['aaguid', 'backedUp', 'counter', 'createdAt', 'credentialId', 'deviceType', 'id', 'name', 'publicKey', 'transports', 'userId'] as const
  $columns = PasskeySchema.$columns
  @column()
  declare aaguid: string | null
  @column()
  declare backedUp: boolean
  @column()
  declare counter: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare credentialId: string
  @column()
  declare deviceType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare publicKey: string
  @column()
  declare transports: string | null
  @column()
  declare userId: string
}

export class ProductSchema extends BaseModel {
  static $columns = ['categories', 'category', 'createdAt', 'expiresAt', 'householdId', 'id', 'imageKey', 'initialQuantity', 'location', 'name', 'openedAt', 'openfoodfactId', 'price', 'quantity', 'receiptId', 'unit', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare categories: any | null
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageKey: string | null
  @column()
  declare initialQuantity: number
  @column()
  declare location: string
  @column()
  declare name: string
  @column.dateTime()
  declare openedAt: DateTime | null
  @column()
  declare openfoodfactId: string | null
  @column()
  declare price: string | null
  @column()
  declare quantity: number
  @column()
  declare receiptId: string | null
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductOutcomeSchema extends BaseModel {
  static $columns = ['amount', 'categories', 'category', 'discardReason', 'expiresAt', 'householdId', 'id', 'kind', 'location', 'occurredAt', 'price', 'productId', 'productName', 'recipeId', 'recordedBy', 'unit'] as const
  $columns = ProductOutcomeSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categories: any | null
  @column()
  declare category: string
  @column()
  declare discardReason: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare location: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare price: string | null
  @column()
  declare productId: string
  @column()
  declare productName: string
  @column()
  declare recipeId: string | null
  @column()
  declare recordedBy: string | null
  @column()
  declare unit: string
}

export class PushTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastDigestOn', 'platform', 'token', 'updatedAt', 'userId'] as const
  $columns = PushTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare lastDigestOn: DateTime | null
  @column()
  declare platform: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class ReceiptSchema extends BaseModel {
  static $columns = ['createdAt', 'householdId', 'id', 'imageKey', 'itemsCount', 'scannedAt', 'storeName', 'totalAmount', 'updatedAt'] as const
  $columns = ReceiptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageKey: string | null
  @column()
  declare itemsCount: number
  @column.dateTime()
  declare scannedAt: DateTime
  @column()
  declare storeName: string
  @column()
  declare totalAmount: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RecipeSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'householdId', 'id', 'imageKey', 'instructions', 'preparationTime', 'source', 'tags', 'title'] as const
  $columns = RecipeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare description: string | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageKey: string | null
  @column()
  declare instructions: string
  @column()
  declare preparationTime: number | null
  @column()
  declare source: string
  @column()
  declare tags: any
  @column()
  declare title: string
}

export class RecipeCookSchema extends BaseModel {
  static $columns = ['cookedAt', 'cookedBy', 'householdId', 'id', 'productsUsed', 'recipeId'] as const
  $columns = RecipeCookSchema.$columns
  @column.dateTime()
  declare cookedAt: DateTime
  @column()
  declare cookedBy: string | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productsUsed: number
  @column()
  declare recipeId: string
}

export class RecipeIngredientSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'productId', 'quantity', 'recipeId', 'unit'] as const
  $columns = RecipeIngredientSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column()
  declare productId: string | null
  @column()
  declare quantity: number | null
  @column()
  declare recipeId: string
  @column()
  declare unit: string | null
}

export class ScanDraftSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'householdId', 'id', 'imageKeys', 'jobId', 'kind', 'payload', 'status'] as const
  $columns = ScanDraftSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageKeys: any
  @column()
  declare jobId: string
  @column()
  declare kind: string
  @column()
  declare payload: any
  @column()
  declare status: string
}

export class SessionSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'ipAddress', 'token', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = SessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class ShoppingItemSchema extends BaseModel {
  static $columns = ['checked', 'createdAt', 'haSyncedAt', 'haUid', 'householdId', 'id', 'name', 'quantity', 'source', 'unit', 'updatedAt'] as const
  $columns = ShoppingItemSchema.$columns
  @column()
  declare checked: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare haSyncedAt: DateTime | null
  @column()
  declare haUid: string | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare quantity: number
  @column()
  declare source: string
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerified', 'id', 'image', 'name', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerified: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class VerificationSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'identifier', 'updatedAt', 'value'] as const
  $columns = VerificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identifier: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string
}
